# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Explore and Visualize IoT Data Class Forum

# Short description (goes below the title; it will also be used in the RSS feed)
description: A Place For Us to Discus The Explore and Visualize IoT Data Coursera Course.

# Your name, as you want it to appear underneath each post and in the footer
author: Jerad Acosta

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
baseurl: /

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://ExporeAndVisualizeIoTData.Jerad.xyz

# Exclude system files
exclude: [.gitignore]

# The disqus shortname for your forum
disqus_shortname: irJERAD

# The public key for your disqus application
disqus_publickey: 2QUUVwOUP76XZOBnEpZbaQAB8gM8kA5AcN8jhg8H1zbuBV7NAO5izVchj3W1nAF4
